### ISSUE TITLE
SourceKit connection interrupt

### ISSUE THREAD

**Issue by depl0y** [realm/jazzy#215]
I upgraded to Jazzy 0.2 by completely uninstalling jazzy and then running `gem install jazzy`, because I wanted Swift 1.2 support.

When I try to run jazzy inside my project folder, after 5 files (always the same file) I get the following error message:

```
Parsing Log.swift (5/139)
sourcekit: [1:connection-event-handler:9811: 0.0000] Connection interrupt
sourcekit: [1:pingService:9811: 0.0005] pinging service
sourcekit: [1:sourcekitd_send_request_sync:1551: 0.0008] request dropped while restoring service
/Users/depl0y/.rvm/gems/ruby-2.2.1/gems/jazzy-0.2.0/lib/jazzy/executable.rb:33:in `execute_command': undefined method `to_S' for #<Jazzy::Executable::IO:0x007fc5c5454da8> (NoMethodError)
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/gems/jazzy-0.2.0/lib/jazzy/sourcekitten.rb:83:in `run_sourcekitten'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/gems/jazzy-0.2.0/bin/jazzy:15:in `<top (required)>'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/bin/jazzy:23:in `load'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/bin/jazzy:23:in `<main>'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/depl0y/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

The file mentioned is the CocoaLumberjack Swift file you need to add to get CocoaLumberjack to work correctly on swift. It's always this file (after 3 test runs at least).

I am running Xcode 6.3.1.

**Comment by jpsim** [comment]
Thanks for filing this! Did a previous version of jazzy work before on CocoaLumberjack (prior to Swift 1.2, of course)?

**Comment by depl0y** [comment]
@jpsim Yes, the previous version working with Swift 1.2 ;) did work without problems on the same project. This file has been in my project since the beginning. 

But in the meanwhile Xcode 6.3 was released, so maybe the problem is a combination of things?

**Comment by jpsim** [comment]
I have 2-3 ideas to fix this, I'll give them a shot tomorrow.

**Comment by odemolliens** [comment]
Same probleme here:

```
Failed to generate documentation
/usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.2.0/lib/jazzy/executable.rb:33:in `execute_command': undefined method `to_S' for #<Jazzy::Executable::IO:0x007fd9c8bf4ab0> (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.2.0/lib/jazzy/sourcekitten.rb:83:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:51:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.2.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

```

**Comment by jpsim** [comment]
@odemolliens the problem you're having is distinctly different. I think I know what's causing it. Can you share which arguments you're passing to jazzy?

**Comment by gutenmorgenuhu** [comment]
Let me throw my hat into the ring:

```
sourcekit: [1:sourcekitd_send_request_sync:1551: 0.0009] request dropped while restoring service
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

**Comment by jpsim** [comment]
@gutenmorgenuhu I can't do much with that. Could you please share a project that reproduces the issue? Thanks!

**Comment by gutenmorgenuhu** [comment]
I narrowed it down. There are some extensions in my folder. If I remove the following exension, jazzy runs without a sourceKitten crash:

```

import Foundation

/**
*  Extension, PopUps */
extension UIViewController : ErrorHandlerDelegate{
 
  /**
  Fehlermeldung
  
  :param: errorMessage Fehlermeldung
  */
  func didCancelWithError(errorMessage: String?) {
    if let errorMessage = errorMessage {
    let alertVC         = UIAlertController(title: TextCollection.ERR, message: errorMessage, preferredStyle: .Alert)
      alertVC.addAction(UIAlertAction(title: TextCollection.ok, style: .Cancel, handler: nil))
      presentViewController(alertVC, animated: true, completion: nil)
    }
  }
  
  /**
  Fehlermeldung mit Titel
  
  :param: errorMessage Fehlermeldung
  :param: title        Titel
  */
  func didCancelWithError(errorMessage: String?, title: String?){
    if let errorMessage = errorMessage, title = title {
    let alertVC         = UIAlertController(title: title, message: errorMessage, preferredStyle: .Alert)
      alertVC.addAction(UIAlertAction(title: TextCollection.ok, style: .Cancel, handler: nil))
      presentViewController(alertVC, animated: true, completion: nil)
    }
  }
  
  /**
  Fehlermeldung mit Titel und Completion-Handler
  
  :param: errorMessage Fehlermeldung
  :param: title        Titel
  :param: completion   Completion-Handler
  */
  func didCancelWithError(errorMessage: String?, title: String?, completion: (() -> Void)?){
    if let errorMessage = errorMessage, title = title {
    let alertVC         = UIAlertController(title: title, message: errorMessage, preferredStyle: .Alert)
      alertVC.addAction(UIAlertAction(title: TextCollection.ok, style: .Cancel, handler: nil))
      presentViewController(alertVC, animated: true, completion: completion)
      
    }
  }

}

```

**Comment by jpsim** [comment]
I believe all of these have been fixed by either Apple in SourceKit or myself in SourceKitten.

If you see another `Connection interrupt` failure, please open a new issue with a Swift sample code that reproduces the failure. Thanks!
