### ISSUE TITLE
'CSSM_VERSION', 'CSSM_GUID' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#451]
Not upgraded to El Capitan, yet. Will see if that solves this. Using Xcode 7.2 for the first time, seeing this:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:99:3: note: 'CSSM_GUID' has been explicitly marked unavailable here
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:143:5: error: 'CSSM_VERSION' is unavailable: not available on iOS

**Comment by Mozahler** [comment]
Forgot to mention also first time using 0.5.0, was running 0.4.1 (sudo gem update jazzy). Never upgrade two things at the same time.

**Comment by Mozahler** [comment]
Sorry, please close this.  It has nothing to do with Jazzy.  Must be a different script I'm running.

**Comment by Mozahler** [comment]
Upgraded to El Capitan, and had to reinstall [sudo gem install jazzy].  Still getting the error (not jazzy, but source kitten):
...
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:384:3: note: 'CSSM_LIST' has been explicitly marked unavailable here
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:465:6: error: 'CSSM_SAMPLEGROUP_PTR' is unavailable: not available on iOS
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:432:68: note: 'CSSM_SAMPLEGROUP_PTR' has been explicitly marked unavailable here
fatal error: too many errors emitted, stopping now [-ferror-limit=]
fatal error: : file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/String+SourceKitten.swift, line 111
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/Users/Alex/Alex/SummerLib2015/SummerLib2015/SummerLib2015_jazzy.h", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk", "-I", "/Users/Alex/Alex/SummerLib2015"] (RuntimeError)

**Comment by jpsim** [comment]
Looks like jazzy can't build your project. Can you please share the command you're passing to jazzy?

What happens when you just run `xcodebuild` in your project?

**Comment by caseycoding** [comment]
I've am getting the same error as well after upgrading to 0.5.0.
```
/Users/casey/Development/sdk-ios/SDK/SDK.h:9:9: fatal error: 'UIKit/UIKit.h' file not found
fatal error: : file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/String+SourceKitten.swift, line 111
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/Users/casey/Development/sdk-ios/SDK/SDK.h", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk", "-I", "/Users/casey/Development/sdk-ios"] (RuntimeError)

fatal error: : file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/String+SourceKitten.swift, line 111
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```
`xcodebuild` builds successfully.

Paired down command that was passed in:
```
jazzy --objc --framework-root . --umbrella-header SDK/SDK.h --skip-undocumented -c
```

**Comment by jpsim** [comment]
@caseycoding that's not the same error at all. Since you're not building for OS X, please specify `--sdk iphoneos` to your jazzy command:

```
jazzy --objc --sdk iphoneos --framework-root . --umbrella-header SDK/SDK.h --skip-undocumented -c
```

**Comment by caseycoding** [comment]
Ahh the back half caught my eye.  Apologies.

**Comment by Mozahler** [comment]
This is my command line:
jazzy --objc --clean --umbrella-header SummerLib2015/SummerLib2015.h --framework-root . -a "Tom Ingemanson"
(was working under 0.4.1)

**Comment by jpsim** [comment]
Ah, maybe I was wrong about @caseycoding's issue being different then. @Mozahler does adding `--sdk iphoneos` work?

**Comment by Mozahler** [comment]
Xcode build looks similar... 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:432:68: note: 'CSSM_SAMPLEGROUP_PTR' has been explicitly marked unavailable here
fatal error: too many errors emitted, stopping now [-ferror-limit=]
building site
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: enum xKitLite.h@Ea, enum xKitLite.h@Ea
jam out ♪♫ to your fresh new docs in `docs`
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

** BUILD SUCCEEDED **

I will try the "sdk iphoneos" next.

**Comment by jpsim** [comment]
@Mozahler if I had access to your project I could help you troubleshoot more too. Is this publicly available?

**Comment by Mozahler** [comment]
No, It isn't in the cloud.  Not my wheelhouse (yet). Point me to a good description and I'll put it in my GitHub space...
I added the sdk to the command line, with slightly different results:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/endian.h:37:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/types.h:95:9: error: unknown type name 'u_int64_t'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
fatal error: : file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/String+SourceKitten.swift, line 111
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/Users/Alex/Alex/SummerLib2015/SummerLib2015/SummerLib2015_jazzy.h", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk", "-I", "/Users/Alex/Alex/SummerLib2015"] (RuntimeError)

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/types.h:37:2: error: architecture not supported

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/endian.h:37:2: error: architecture not supported

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/types.h:95:9: error: unknown type name 'u_int64_t'

fatal error: too many errors emitted, stopping now [-ferror-limit=]

fatal error: : file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/String+SourceKitten.swift, line 111
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment]
Can you just email me your project please? jp@realm.io thanks.

**Comment by Mozahler** [comment]
I'll figure it out and get it to you. I tried setting up email on my dev machine but didn't  remember the email password. Spent an hour on hold to verizon yesterday account... still locked up.

**Comment by esad** [comment]
I'm having the same problem with various ruby versions and Jazzy 0.5.0.

When I manually run the sourcekitten it terminates with

```
fatal error: : file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/String+SourceKitten.swift, line 111
Illegal instruction: 4
```

I narrowed it down to a public header that has two categories defined:

```
#import <Foundation/Foundation.h>

@interface ObjCTopLevelClass : NSObject
@end

@interface ObjCTopLevelClass (SomeCategory)
/// Extends ObjCTopLevelClass in mysterious ways
- (void)categoryMethod:(NSString*)argument;
@end

@interface ObjCTopLevelClass (MarkedCategory)
#pragma mark Some marker
/// Extends ObjCTopLevelClass in even more mysterious ways
- (void)markedCategoryMethod:(NSString*)argument;
@end
```

When I comment out one of the categories it works fine

**Comment by esad** [comment]
Probably related: 

https://github.com/jpsim/SourceKitten/commit/3c063ae8141dd6b37e2dc08298d0d2b3a145845f

which seems to have been fixed with SourceKitten 0.10

**Comment by Mozahler** [comment]
Thank you. I will try that and if it succeeds update my post. 
M

**Comment by jpsim** [comment]
@Mozahler closing this since we never heard back from you since your last post here. Please open a new issue if you're still having trouble.

**Comment by Mozahler** [comment]
Thank you. I started looking into it after upgrading to 0.6.0 yesterday. Let me resolve what I can on my own (still having issues with --sdk option)
So happy to see such progress on your project - especially Objective C integration. 

                          🐢💨
