### ISSUE TITLE
Build 0.13.3 does not properly handle "embedded" framework (swift) - Used to work with 0.13.1

### ISSUE THREAD

**Issue by jcdulacnextshotinc** [realm/jazzy#1186]
My project depends on a framework and when jazzy run xcodebuild the build fails when compiling a file depending on this external module. The project builds fine under XCode normal usage. The documentation generation used to work correctly with jazzy 0.13.1.

Thanks.

For info here is the error message:
/Users/next-shot/Desktop/GSEM/GSEM/Triangulation.swift:10:8: error: no such module 'CDT'
import CDT
       ^

** BUILD FAILED **

The following build commands failed:
        CompileSwift normal arm64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler

**Comment by johnfairh** [comment]
> builds fine under XCode normal usage.

Do you mean that running `xcodebuild` from the command line works?

Latest jazzy fixed a thing whereby build problems were sometimes not noticed, which led users to have incomplete or empty docs.  It could be that your project was silently suffering from that -- might be you need to pass `-scheme xyz` to get the `CDT` dependency built for this code to build.

**Comment by jcdulacnextshotinc** [comment]
Thanks for the quick reply.

When I say that Xcode build works fine, it is through the XCode interface. With 0.13.1 I have all my classes documented, so the problem is not a silent build error.

Jean-Claude Dulac

On May 1, 2020, at 4:32 AM, John Fairhurst <notifications@github.com> wrote:

﻿

builds fine under XCode normal usage.

Do you mean that running xcodebuild from the command line works?

Latest jazzy fixed a thing whereby build problems were sometimes not noticed, which led users to have incomplete or empty docs. It could be that your project was silently suffering from that -- might be you need to pass -scheme xyz to get the CDT dependency built for this code to build.

**Comment by johnfairh** [comment]
You'll need to run `xcodebuild` and see why it's not building cleanly.  I guess the problem is the CLI default (which is often different to the Xcode GUI default ⌘B) is not good enough and you will need to pass some flags to make it behave the same way.

**Comment by jcdulacnextshotinc** [comment]
Thanks again. So, as you suggested I ran:

xcodebuild -scheme GSEM

and this was successful.

Now when I run jazzy:

jazzy -o class-docs --config ./.jazzy.json --build-tool-arguments "-scheme GSEM”

I get the following error:

xcodebuild: error: invalid option '-scheme GSEM’

When I try to add the build-tool-arguments to the .jazzy.json  I get the following error:

WARNING: Unknown config file attribute "build-tool-arguments”

If I try to remove the quotes and run:

jazzy -o class-docs --config ./.jazzy.json --build-tool-arguments -scheme GSEM

I get the following error:

xcodebuild: error: The project named "GSEM" does not contain a scheme named "-showBuildSettings". The "-list" option can be used to find the names of the schemes in the project.

So, I think I need a fix to remove the quote from the argument sent to xcodebuild. It would be also nice to have the build-tool-arguments taken into account in the .jazzy.json file to be consistent.

Thanks.

Jean-Claude Dulac
Next-Shot LLC - www.next-shot-inc.com<http://www.next-shot-inc.com>
jcdulac@next-shot-inc.com<mailto:jcdulac@next-shot-inc.com>

On May 1, 2020, at 12:15 PM, John Fairhurst <notifications@github.com<mailto:notifications@github.com>> wrote:



You'll need to run xcodebuild and see why it's not building cleanly. I guess the problem is the CLI default (which is often different to the Xcode GUI default ⌘B) is not good enough and you will need to pass some flags to make it behave the same way.

**Comment by johnfairh** [comment]
Thanks for struggling on.

The CLI syntax is `jazzy --build-tool-arguments -scheme,GSEM`

The json syntax would be (I think, I'm more used to yaml):
```json
{
  "build_tool_arguments" : ["-scheme", "GSEM"]
}
```

(the CLI-hyphens-become-config-underscores is from way before I got involved in the project, you know as much as I do!)

**Comment by jcdulacnextshotinc** [comment]
Many thanks for your help. It works. I will close the issue.

if I had one suggestion, it would be to increase the level of documentation with more examples.

I could not have guess the transformation from “-scheme GSEM” to “-scheme,GSEM”. For me, the comma separated argument list was for composing multiple options, like “-scheme GSEM”,”-project XXX”, etc.
In the same category of more examples are needed, I struggle very much to understand the full utilization of the custom-categories.

Thanks again.

Jean-Claude Dulac
Next-Shot LLC - www.next-shot-inc.com<http://www.next-shot-inc.com>
jcdulac@next-shot-inc.com<mailto:jcdulac@next-shot-inc.com>

On May 1, 2020, at 3:51 PM, John Fairhurst <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for struggling on.

The CLI syntax is jazzy --build-tool-arguments -scheme,GSEM

The json syntax would be (I think, I'm more used to yaml):

{
  "build_tool_arguments" : ["-scheme", "GSEM"]
}

(the CLI-hyphens-become-config-underscores is from way before I got involved in the project, you know as much as I do!)

**Comment by JenniferBrooks39** [comment]
> My project depends on a framework and when jazzy run xcodebuild the build fails when compiling a file depending on this external module. The project builds fine under XCode normal usage. The documentation generation used to work correctly with jazzy 0.13.1.
> 
> Thanks.
> 
> For info here is the error message:
> /Users/next-shot/Desktop/GSEM/GSEM/Triangulation.swift:10:8: error: no such module 'CDT'
> import CDT
> ^
> 
> ** BUILD FAILED **
> 
> The following build commands failed:
> CompileSwift normal arm64
> CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler

**Comment by JenniferBrooks39** [comment]
#
Duplicate of #``
